# Generated by Django 2.2.7 on 2019-12-10 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='gender',
        ),
        migrations.AddField(
            model_name='driver',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
