# Generated by Django 2.2.7 on 2019-12-14 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20191210_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_of_issuance', models.CharField(blank=True, max_length=250, null=True)),
                ('class_of_liscense', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_replacement', models.CharField(blank=True, max_length=250, null=True)),
                ('license_of_number', models.CharField(blank=True, max_length=250, null=True)),
                ('chassess_number', models.CharField(blank=True, max_length=250, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=250, null=True)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='any_form_of_disability',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='blood_group',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='educational_background',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email_address',
            field=models.EmailField(default='bs@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='height',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='local_government',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='nationality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='next_of_kin_phone_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='previous_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
