# Generated by Django 2.2.7 on 2019-12-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20191214_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldnumber',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldnumber',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
