# Generated by Django 2.2.7 on 2019-12-14 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20191214_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldnumber',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldnumber',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
