# Generated by Django 2.2.7 on 2019-12-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20191215_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldnumber',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
        ),
    ]
