# Generated by Django 2.2.7 on 2020-01-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_auto_20191215_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='chassess_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='class_of_liscense',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_of_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='number_of_replacement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='plate_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='state_of_issuance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
